### ISSUE TITLE
SND aerotech motor not compatible with mvr in xcs3

### ISSUE THREAD

**Issue by Yanwen-Sun** [pcdshub/hxrsnd#107]
In [3]: snd.t1.th1.mvr(1e-3)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-e5a8efdb3272> in <module>
----> 1 snd.t1.th1.mvr(1e-3)

/reg/g/pcds/pyps/apps/hutch-python/common/dev/devpath/pcdsdevices/interface.py in mvr(self, delta, timeout, wait, log)
    663         """
    664 
--> 665         self.mv(delta + self.wm(), timeout=timeout, wait=wait, log=log)
    666 
    667     def umv(self, position, timeout=None, log=True, newline=True):

/reg/g/pcds/pyps/apps/hutch-python/xcs/dev/devpath/hxrsnd/aerotech.py in mv(self, position, wait, print_move, *args, **kwargs)
    279         """
    280         try:
--> 281             status = self.move(position, wait=wait, *args, **kwargs)
    282 
    283             # Notify the user that a motor has completed or the command is sent

/reg/g/pcds/pyps/apps/hutch-python/xcs/dev/devpath/hxrsnd/aerotech.py in move(self, position, wait, check_status, timeout, *args, **kwargs)
    233         logger.debug("Moving {0} to {1}".format(self.name, position))
    234         return super().move(position, wait=wait, timeout=timeout, *args,
--> 235                             **kwargs)
    236 
    237     def mv(self, position, wait=True, print_move=True,

/reg/g/pcds/pyps/apps/hutch-python/common/dev/devpath/pcdsdevices/interface.py in move(self, *args, **kwargs)
    525 
    526     def move(self, *args, **kwargs):
--> 527         st = super().move(*args, **kwargs)
    528         self._last_status = st
    529         return st

/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/ophyd/utils/epics_pvs.py in wrapper(self, *args, **kwargs)
    196     def wrapper(self, *args, **kwargs):
    197         if self.connected:
--> 198             return fcn(self, *args, **kwargs)
    199         else:
    200             raise DisconnectedError('{} is not connected'.format(self.name))

/u1/conda/pcds-3.3.4/lib/python3.6/site-packages/ophyd/epics_motor.py in move(self, position, wait, **kwargs)
    170         self._started_moving = False
    171 
--> 172         status = super().move(position, **kwargs)
    173         self.user_setpoint.put(position, wait=False)
    174         try:

TypeError: move() got an unexpected keyword argument 'log'

**Comment by klauer** [comment]
Thanks for reporting this, @Yanwen-Sun - I'll fix this and push an update to you soon.

**Comment by klauer** [comment]
@Yanwen-Sun this update will be available in `xcs3` when you restart the session. 

Please open more issues as you run into them and we'll do our best to help you get going as quickly as possible. 👍
