### ISSUE TITLE
snd.delay.mv

### ISSUE THREAD

**Issue by Yanwen-Sun** [pcdshub/hxrsnd#111]
In [24]: snd.delay.mv(-5)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-24-bd05408685a4> in <module>
----> 1 snd.delay.mv(-5)

/reg/g/pcds/pyps/apps/hutch-python/xcs/dev/devpath/hxrsnd/macromotor.py in mv(self, position, wait, verify_move, use_diag, *args, **kwargs)
    283         try:
    284             return super().mv(position, wait=wait, verify_move=verify_move,
--> 285                               use_diag=use_diag, *args, **kwargs)
    286         # Catch all the common motor exceptions
    287         except LimitError:

TypeError: mv() got an unexpected keyword argument 'verify_move'

**Comment by Yanwen-Sun** [comment]
Also, the verify_move default is True previously, is it now compatible with x.ascan? How do I set it to false in the scan? Or we need to set the default to False.

**Comment by klauer** [comment]
I'm making a workaround for this feature now. 

Would it be OK for this to be a thing you set on the device itself, e.g., `snd.delay.verify_move = True` when you want to use it? It'd then be at your discretion when to enable/disable it.

**Comment by Yanwen-Sun** [comment]
Yes. I think that is what we want to do for now

**Comment by klauer** [comment]
@Yanwen-Sun I have a proposed fix in #112 - but will need someone to push it to you on the beamline as I lack permission to do so (@ZryletTC @ZLLentz if you're still around...)

**Comment by Yanwen-Sun** [comment]
Ok. We need this tonight. Who else have the permission you can think of?

**Comment by ZLLentz** [comment]
I'm still around. Do you want this exact branch?

**Comment by ZryletTC** [comment]
Yeah, I'll be around til this is all working. I can do the pull in just a sec.

**Comment by klauer** [comment]
I'm sure it's still not 100%, but I think we should merge the PR (unless there's anything obviously wrong) and go from there. 🤞
