### ISSUE TITLE
Coloredlogs overwrites the stream handler's formatting

### ISSUE THREAD

**Issue by apra93** [pcdshub/hxrsnd#63]
## Expected Behavior

All messages have the same format but are colored.

## Current Behavior

The message format is the default colored logs format rather than what is defined in the `logging.yml` file.

## Possible Solution

Easiest thing is to just pass the format from the config file into the install.

**Comment by ZLLentz** [comment]
Found a solution to this in `hutch-python`, check out https://github.com/pcdshub/hutch-python/blob/master/logging.yml and https://github.com/pcdshub/hutch-python/blob/master/hutch_python/log_setup.py

Summary:
- Change `logging.yml` to include the coloredlogs formatter using the custom formatter syntax
- remove the coloredlogs install line from `setup_logging`
